# Generated by Django 5.2.1 on 2025-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/category/nonfiction.jpg', upload_to='uploads/category'),
        ),
    ]
