# Generated by Django 5.2.1 on 2025-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
